apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-kcsl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/vigneshsri-tenant/devfile-sample-go-basic-1/devfile-sample-go-basic-kcsl@sha256:925ef6f292d92555a66de6c26d7bde453b1044953f83c609a4d441af4cdcb734
        name: my-go
        resources: {}
status: {}
